/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/layouts/AdminLayout/AdminLayout.vue')['default']
    Application: typeof import('./src/components/Application/Application.vue')['default']
    AppLoading: typeof import('./src/components/AppLoading/AppLoading.vue')['default']
    BasicContain: typeof import('./src/components/BasicContain/BasicContain.vue')['default']
    BasicLayout: typeof import('./src/layouts/BasicLayout/BasicLayout.vue')['default']
    BlankLayout: typeof import('./src/components/BlankLayout/BlankLayout.vue')['default']
    CsIcon: typeof import('./src/components/CsIcon/CsIcon.vue')['default']
    CsTable: typeof import('./src/components/CsTable/index.vue')['default']
    DialogContent: typeof import('./src/components/DialogContent/DialogContent.vue')['default']
    LayoutAside: typeof import('./src/layouts/components/LayoutAside.vue')['default']
    LayoutHeader: typeof import('./src/layouts/components/LayoutHeader.vue')['default']
    MessageContent: typeof import('./src/components/MessageContent/MessageContent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NotificationContent: typeof import('./src/components/NotificationContent/NotificationContent.vue')['default']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
